### PR TITLE
Added two file

### PR DESCRIPTION
**Pull request by bulbicx**
hey hey

### CODE REVIEW

**Review by davealgie — COMMENTED** [review]
I approve these files

**Review by Leaf-Cooper-QA — APPROVED** [review]
No puns, dissapointed but acceptable

**Comment by davealgie** [comment]
Approved

**Review by davealgie — COMMENTED** [review]
nice puns sir

**Comment by davealgie** [comment]
attempted to figure it out

**Review by davealgie — COMMENTED** [review]
Good scenario

**Review by davealgie — APPROVED** [review]

**Review by ghost — APPROVED** [review]
hey man

**Pull request merged**
